baseURL = ""
title = "SOFAStack"

languageCode = "zh-CN"
defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true
enableGitInfo = true

disableKinds = ["taxonomyTerm"]

Paginate = 10
googleAnalytics = "UA-142131411-1"

[params]
	github = "https://github.com/sofastack/sofastack.tech"
	# legacyWebsite = "http://legacy.sofastack.tech"
	description = "SOFAStack is a Scalable Open Financial Architecture for building cloud native applications"
	favicon = "https://gw.alipayobjects.com/os/q/cms/images/jqu9346l/4ba95631-2489-4885-881f-bc7f8d787d5e_w64_h61.png"

# 首页订阅
[params.homeSubscription]
	enable = false

# algolia
[outputFormats.Algolia]
	baseName = "algolia"
	isPlainText = true
	mediaType = "application/json"
	notAlternative = true

[params.algolia]
	vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
	params = ["categories", "tags", "series"]

[outputs]
 home = ["HTML", "RSS", "Algolia"]

[languages]
	[languages.en]
	contentDir = "content/en"
	languageName = "English"
	weight = 10
	[languages.zh]
		contentDir = "content/zh"
		languageName = "中文"
		weight = 20

	[[languages.zh.menu.main]]
		identifier = "projects"
		name = "项目"
		url = "/projects/"
		weight = 1
	[[languages.zh.menu.main]]
		identifier = "guides"
		name = "指南"
		url = "/guides/"
		weight = 2
	[[languages.zh.menu.main]]
		identifier = "blog"
		name = "博客"
		url = "/blog/"
		weight = 3
	[[languages.zh.menu.main]]
		identifier = "activities"
		name = "活动"
		url = "/activities/"
		weight = 4
	[[languages.zh.menu.main]]
		identifier = "awesome"
		name = "Awesome SOFA"
		url = "/awesome/"
		weight = 6
	[[languages.zh.menu.main]]
		identifier = "community"
		name = "社区"
		url = "/community/"
		weight = 5

[menu]
	[[menu.main]]
		identifier = "projects"
		name = "Projects"
		url = "/en/projects/"
		weight = 1
	[[menu.main]]
		identifier = "guides"
		name = "Guides"
		url = "/en/guides/"
		weight = 2
	[[menu.main]]
		identifier = "blog"
		name = "Blog"
		url = "/en/blog/"
		weight = 3
	[[menu.main]]
		identifier = "activities"
		name = "Activity"
		url = "/en/activities/"
		weight = 4
	[[menu.main]]
		identifier = "awesome"
		name = "Awesome SOFA"
		url = "/awesome/"
		weight = 6
	[[languages.zh.menu.main]]
		identifier = "community"
		name = "Community"
		url = "/community/"
		weight = 5

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
